In [305]:
from pathlib import Path
import numpy as np
import pandas as pd



In [357]:
mat = np.zeros((10000, 3), np.int32)
i = 0
fout = open("out.npy", "wb")
fs = Path(".bookworm/texts/encoded/unigrams/").glob("*.txt")
for f in fs:
    all = pd.read_csv(f, sep="\t", names = ["bookid", "wordid", "count"], dtype=np.int32)
    all = all[["wordid", "bookid", "count"]]
    np_version = all.to_numpy()
#    np_version = np_version[100:230,:]
    fout.write(np_version.tobytes())
    print(f)
#    break
fout.close()

.bookworm/texts/encoded/unigrams/188ecdd1c15ac888737fea845c7c5d.txt
.bookworm/texts/encoded/unigrams/cf094e496a9cfd47eb5808da8d5b54.txt
.bookworm/texts/encoded/unigrams/0d2ee30350443430f36abcb3f90fbd.txt
.bookworm/texts/encoded/unigrams/e32562a376972681f3ab38bc405ac6.txt
.bookworm/texts/encoded/unigrams/b6d5d5ac3358555dfb4830a54d19c0.txt
.bookworm/texts/encoded/unigrams/57cb65cecd910930a55860cca7462d.txt


In [358]:
p = Path("out.npy")
p.stat().st_size

93724296

In [359]:
#np.memmap(self.path, dtype='int32', mode='r+', shape=(self.nrow, 1))

In [461]:
class Count_Array():
    def __init__(self, fn, grams = 1):
        self.path = Path(fn)
        self.fsize = p.stat().st_size
        self.nrow = int(self.fsize/(4 + 4 + grams * 4))
        self.mat = np.memmap(self.path, dtype='int32', mode='r+', shape=(self.nrow, 2 + grams))
    def sort(self):
        self.mat.view('i4, i4, i4').sort(order=['f0'], axis=0)
    def bisect_left(self, x, lo = 0, hi = None):
        if hi is None:
            hi = self.mat.shape[0]
        max = hi
        cap = hi
        while lo < hi:
            mid = (lo + hi) // 2
            if x < self.mat[mid][0]:
                hi = mid
            else:
                lo = mid + 1
        return lo
    def counts(self, x):
        left = self.bisect_left(x-1, 0, None)
        right = self.bisect_left(x, left, None)
#        print(left, right)
        return self.mat[left:right,1:]
    def countframe(self, ix):
        c = self.counts(ix)
        return pd.DataFrame(c[:,1], columns=["count"], index=c[:,0])
    def all_counts(self, ixes):
        c = self.countframe(ixes.pop())
        while len(ixes) > 0:\
            c += self.countframe(ixes.pop())
        return c
    
g = Count_array(p)
g.all_counts([2, 10]).sum()

count    2587203
dtype: int64

In [459]:
%timeit g.all_counts([5, 15]).sum()

2.63 ms ± 669 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [443]:
g.counts(1000)
from collections import Counter
#Counter(
pd.DataFrame(g.counts(1000)[:,1], columns=["count"], index=g.counts(1000)[:,0])

1997802 1999201
1997802 1999201
1997802 1999201


count
3         1
4         1
6         5
8         3
11        4
...     ...
2492      4
2493      2
2494      3
2495      4
2496      5

[1399 rows x 1 columns]

In [438]:
from pandas import DataFrame


B
A     
0  7.0
1  7.0
2  4.0

In [272]:
fp = g.mat
fp.sort(axis=0)
fp[15]

memmap([0, 1, 1], dtype=int32)

In [279]:
for l in fp[6000000:]:
    if l[0]==50000:
        print(l)

[50000  2438    36]
[50000  2438    36]
[50000  2438    36]
[50000  2438    36]
[50000  2438    36]


In [351]:
g = np.array([[10916,     3,    24],
       [ 1222,     3,     1],
       [ 4241,     3,     3],
       [12607,     3,     1],
       [ 4377,     3,     3],
       [13284,     3,     1],
       [17558,     3,     1],
       [ 6981,     3,     3],
       [ 4248,     3,     1],
       [ 7112,     3,     1],
       [ 4524,     3,     1],
       [ 1612,     3,     1],
       [ 8952,     3,     1],
       [ 8470,     3,     1],
       [ 1779,     3,     1],
       [ 2327,     3,     3],
       [  645,     3,     1],
       [16029,     3,     1],
       [ 1554,     3,     1],
       [ 2393,     3,     2],
       [58008,     3,     1],
       [17582,     3,     3],
       [ 4225,     3,     1],
       [ 3015,     3,     1],
       [49932,     3,     4],
       [45123,     3,     1],
       [  576,     3,     1],
       [  237,     3,     7],
       [ 5323,     3,     1],
       [ 3067,     3,     1],
       [59578,     3,     9],
       [51873,     3,     1],
       [ 4433,     3,     2],
       [  537,     3,     1],
       [46699,     3,     1],
       [21764,     3,     1],
       [ 2045,     3,     1],
       [ 2415,     3,     4],
       [ 1578,     3,     1],
       [ 6238,     3,     1],
       [13214,     3,     1],
       [ 7761,     3,     1],
       [37302,     3,     1],
       [28867,     3,     1],
       [ 2769,     3,     1],
       [  816,     3,     2],
       [  660,     3,     1],
       [28787,     3,     1],
       [ 3526,     3,     2],
       [  680,     3,     5],
       [11280,     3,     2],
       [ 3090,     3,     1],
       [46904,     3,     1],
       [  911,     3,     6],
       [ 2191,     3,     5],
       [12962,     3,     1],
       [  299,     3,     7],
       [ 8054,     3,     1],
       [ 1846,     3,     1],
       [ 4793,     3,     1],
       [  782,     3,     1],
       [  694,     3,     4],
       [12105,     3,     1],
       [10335,     3,     1],
       [45145,     3,     3],
       [24178,     3,     1],
       [ 2025,     3,     1],
       [12523,     3,     8],
       [  301,     3,    18],
       [35460,     3,     1],
       [21571,     3,     5],
       [12459,     3,     2],
       [24912,     3,     1],
       [ 5289,     3,     3],
       [  784,     3,     1],
       [ 2554,     3,     1],
       [   36,     3,    97],
       [13077,     3,     1],
       [ 1863,     3,     1],
       [  279,     3,    21],
       [  618,     3,     1],
       [28761,     3,     8],
       [32330,     3,    10],
       [ 2518,     3,     3],
       [  226,     3,    12],
       [ 4295,     3,    21],
       [ 1597,     3,     5],
       [    8,     3,   190],
       [ 2820,     3,     5],
       [  185,     3,     5],
       [  168,     3,    26],
       [46887,     3,     1],
       [ 2865,     3,     3],
       [13199,     3,     1],
       [  424,     3,     2],
       [14044,     3,     9],
       [   60,     3,    23],
       [ 1260,     3,    12],
       [10575,     3,     1],
       [ 1841,     3,     4],
       [  505,     3,     5],
       [ 5420,     3,     2],
       [39250,     3,     1],
       [ 2620,     3,     1],
       [  640,     3,     3],
       [11793,     3,     2],
       [  926,     3,     4],
       [40055,     3,    12],
       [14235,     3,     1],
       [21855,     3,    10],
       [10272,     3,     1],
       [  387,     3,    19],
       [51759,     3,     2],
       [ 2801,     3,     1],
       [ 4794,     3,     1],
       [53160,     3,     1],
       [  516,     3,     3],
       [ 1174,     3,     2],
       [69105,     3,     2],
       [  448,     3,     3],
       [ 8619,     3,     1],
       [ 5589,     3,     3],
       [41915,     3,     4],
       [ 3921,     3,     1],
       [ 2640,     3,     3],
       [ 1455,     3,     1],
       [  515,     3,     2],
       [47977,     3,     4],
       [54747,     3,     1],
       [36909,     3,     1]])

[[10916,     3,    24],
       [ 1222,     3,     1],
       [ 4241,     3,     3],
       [12607,     3,     1],
       [ 4377,     3,     3],
       [13284,     3,     1],
       [17558,     3,     1],
       [ 6981,     3,     3],
       [ 4248,     3,     1],
       [ 7112,     3,     1],
       [ 4524,     3,     1],
       [ 1612,     3,     1],
       [ 8952,     3,     1],
       [ 8470,     3,     1],
       [ 1779,     3,     1],
       [ 2327,     3,     3],
       [  645,     3,     1],
       [16029,     3,     1],
       [ 1554,     3,     1],
       [ 2393,     3,     2],
       [58008,     3,     1],
       [17582,     3,     3],
       [ 4225,     3,     1],
       [ 3015,     3,     1],
       [49932,     3,     4],
       [45123,     3,     1],
       [  576,     3,     1],
       [  237,     3,     7],
       [ 5323,     3,     1],
       [ 3067,     3,     1],
       [59578,     3,     9],
       [51873,     3,     1],
       [ 4433,     3,     2],
       [  537,     3,     1],
       [46699,     3,     1],
       [21764,     3,     1],
       [ 2045,     3,     1],
       [ 2415,     3,     4],
       [ 1578,     3,     1],
       [ 6238,     3,     1],
       [13214,     3,     1],
       [ 7761,     3,     1],
       [37302,     3,     1],
       [28867,     3,     1],
       [ 2769,     3,     1],
       [  816,     3,     2],
       [  660,     3,     1],
       [28787,     3,     1],
       [ 3526,     3,     2],
       [  680,     3,     5],
       [11280,     3,     2],
       [ 3090,     3,     1],
       [46904,     3,     1],
       [  911,     3,     6],
       [ 2191,     3,     5],
       [12962,     3,     1],
       [  299,     3,     7],
       [ 8054,     3,     1],
       [ 1846,     3,     1],
       [ 4793,     3,     1],
       [  782,     3,     1],
       [  694,     3,     4],
       [12105,     3,     1],
       [10335,     3,     1],
       [45145,     3,     3],
       [24178,     3,     1],
       [ 2025,     3,     1],
       [12523,     3,     8],
       [  301,     3,    18],
       [35460,     3,     1],
       [21571,     3,     5],
       [12459,     3,     2],
       [24912,     3,     1],
       [ 5289,     3,     3],
       [  784,     3,     1],
       [ 2554,     3,     1],
       [   36,     3,    97],
       [13077,     3,     1],
       [ 1863,     3,     1],
       [  279,     3,    21],
       [  618,     3,     1],
       [28761,     3,     8],
       [32330,     3,    10],
       [ 2518,     3,     3],
       [  226,     3,    12],
       [ 4295,     3,    21],
       [ 1597,     3,     5],
       [    8,     3,   190],
       [ 2820,     3,     5],
       [  185,     3,     5],
       [  168,     3,    26],
       [46887,     3,     1],
       [ 2865,     3,     3],
       [13199,     3,     1],
       [  424,     3,     2],
       [14044,     3,     9],
       [   60,     3,    23],
       [ 1260,     3,    12],
       [10575,     3,     1],
       [ 1841,     3,     4],
       [  505,     3,     5],
       [ 5420,     3,     2],
       [39250,     3,     1],
       [ 2620,     3,     1],
       [  640,     3,     3],
       [11793,     3,     2],
       [  926,     3,     4],
       [40055,     3,    12],
       [14235,     3,     1],
       [21855,     3,    10],
       [10272,     3,     1],
       [  387,     3,    19],
       [51759,     3,     2],
       [ 2801,     3,     1],
       [ 4794,     3,     1],
       [53160,     3,     1],
       [  516,     3,     3],
       [ 1174,     3,     2],
       [69105,     3,     2],
       [  448,     3,     3],
       [ 8619,     3,     1],
       [ 5589,     3,     3],
       [41915,     3,     4],
       [ 3921,     3,     1],
       [ 2640,     3,     3],
       [ 1455,     3,     1],
       [  515,     3,     2],
       [47977,     3,     4],
       [54747,     3,     1],
       [36909,     3,     1]]
g.view('i8, i8, i8').sort(order=['f0'], axis=0)
g

array([[    8,     3,   190],
       [   36,     3,    97],
       [   60,     3,    23],
       [  168,     3,    26],
       [  185,     3,     5],
       [  226,     3,    12],
       [  237,     3,     7],
       [  279,     3,    21],
       [  299,     3,     7],
       [  301,     3,    18],
       [  387,     3,    19],
       [  424,     3,     2],
       [  448,     3,     3],
       [  505,     3,     5],
       [  515,     3,     2],
       [  516,     3,     3],
       [  537,     3,     1],
       [  576,     3,     1],
       [  618,     3,     1],
       [  640,     3,     3],
       [  645,     3,     1],
       [  660,     3,     1],
       [  680,     3,     5],
       [  694,     3,     4],
       [  782,     3,     1],
       [  784,     3,     1],
       [  816,     3,     2],
       [  911,     3,     6],
       [  926,     3,     4],
       [ 1174,     3,     2],
       [ 1222,     3,     1],
       [ 1260,     3,    12],
       [ 1455,     3,     1],
       [ 1

In [267]:
fp[250657]

memmap([5926,  474,    1], dtype=int32)

In [208]:
g.mat[7810357][0]

89577

In [191]:
np.apply_along_axis(lambda a: a.searchsorted(950), axis = 0, arr = )


NameError: name 'numpy' is not defined